version: '3.8'

services:
  percobaan3:
    container_name: percobaan3
    image: percobaan2
    build: 
      context: .
    ports:
      - "5500:5500"
    depends_on:
      - pgsqldb
  
  pgsqldb:
    container_name: pgsqldb
    image: "postgres:12"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=admin
    volumes:
      - todo_data:/var/lib/postgresql/data

volumes:
  todo_data: {}
